server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://login-service-db:5432/login-service-db
    username: l_user
    password: l_password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    function:
      definition: publishUser;
    stream:
      bindings:
        publishUser-out-0:
          destination: user.management

  kafka:
    bootstrap-servers: broker:9092