server:
  port: 8086
spring:
  application:
    name: marktag-service
  datasource:
    username: 'yuj98'
    url: jdbc:postgresql://${PSQL_IP:localhost}:5432/marktag-service-db
    #url: jdbc:postgresql://localhost:5438/marktag-service-db
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

  kafka:
    #bootstrap-servers: localhost:9092
    bootstrap-servers: broker:9092





