stages:
  - build
  - unit-test
  - integration-test
  - end-to-end-test

maven-build:
  stage: build
  tags:
    - ase-0601
  image: maven:3.9.1
  script:
    - cd implementation
    - mvn clean package -Dmaven.test.skip --projects !edu.ems:frontend
  artifacts:
    paths:
      - implementation/*/target/*.jar
    expire_in: 5 mins

unit-tests:
  stage: unit-test
  tags:
    - ase-0601
  image: maven:3.9.1
  script:
    - cd implementation/notification-service
    - mvn test -Dtest=EventRepositoryTest

integration-tests:
  stage: integration-test
  tags:
    - ase-0601
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd implementation/notification-service
    - docker build --build-arg SKIP_TESTS_BUILD="true" -f Dockerfile.integration -t integration-tests .
    - cd ../
    - docker-compose up --build -d notification-service-db zookeeper broker
    - cd ./notification-service
    - docker run -e SKIP_TESTS_RUN="false" --network implementation_default integration-tests
    - cd ../
    - docker-compose down
    - docker system prune --all --force --volumes

end-to-end-test:
  stage: end-to-end-test
  tags:
    - ase-0601
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd ./implementation/end-to-end
    - docker build -t end-to-end-tests -f Dockerfile .
    - cd ../
    - docker-compose up --build -d api-gateway login-service feedback-service analyticsandreport-service event-inventory-service marktag-service export-service attendance-service recommender-service notification-service
    - cd ./end-to-end
    - sleep 100s
    - docker run --network implementation_default end-to-end-tests
    - cd ../
    - docker-compose down
    - docker system prune --all --force --volumes
